-- AlterTable
ALTER TABLE `lamaran` MODIFY `status` ENUM('PENDING_BERKAS', 'BERKAS_DITERIMA', 'BERKAS_DITOLAK', 'INTERVIEW_DIJADWALKAN', 'LOLOS_INTERVIEW', 'TIDAK_LOLOS_INTERVIEW', 'DITERIMA_MAGANG', 'KONFIRMASI_DITERIMA', 'DITOLAK') NOT NULL DEFAULT 'PENDING_BERKAS';
